target_dataset: 
  batch_size: 16
  seed: 123456
  train_fraction: 1
  num_workers: 2

target_transform:
  height: 256

pipeline:
  params:
    model: 
      name: "resnet18"
      pretrained: True

weights:

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: "test"
  project: "thesis"

checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val_loss"


defaults:
  - target_dataset: chest14
  - transform: basic
  - pipeline: baselineAdam
